apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: PGSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-rootpass
                  key: password
            - name: POSTGRES_DB
              value: storedb
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: admin
          image: {{ .Values.db.deployment.image }}
          name: db
          ports:
            - containerPort: {{ .Values.db.service.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
       - name: postgres-data
         persistentVolumeClaim:
           claimName: postgres-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast
  namespace: {{ .Values.namespace }}
  labels:
    app: cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        network/apinetwork: "true"
        app: cast
    spec:
      containers:
        - image: {{ .Values.cast.deployment.image }}
          imagePullPolicy: Always  
          name: cast
          ports:
            - containerPort: {{ .Values.cast.service.port }}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  namespace: {{ .Values.namespace }}
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        network/apinetwork: "true"
        app: movie
    spec:
      containers:
        - image: {{ .Values.movie.deployment.image }}
          imagePullPolicy: Always  
          name: movie
          ports:
            - containerPort: {{ .Values.movie.service.port }}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        network/apinetwork: "true"
        app: nginx
    spec:
      containers:
        - image: {{ .Values.nginx.deployment.image }}
          imagePullPolicy: Always  
          name: nginx
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: nginx-conf
          hostPath:
            path: {{ .Values.nginx.volumes.hostPath }}

      restartPolicy: Always

